clustersecretstore:
  name: cluster-azure-backend
  providerType: azurekv
  azurekv:
    tenantid: "" # Azure Tenant ID
    vaulturl: "" # Azure Keyvault URL
    identityid: "changeme"  #ManagedIdentity ClientID
  #name: hcp-vault-backend
  #providerType: vault
  #vault:
  #  server: "https://vault.marcusaleksandravicius.com"
  #  path: "path-test"
  #  version: "v2"
  #  auth:
  #    tokenName: "vault-token"
  #    tokenNamespace: secretsoperator
  #    tokenKey: "vault-token"
## FOR SP AUTHENTICATION
  #clientid:
  #  name: azure-secret-sp
  #  namespace: eso
  #  id: ClientID
  #clientsecret:
  #  name: azure-secret-sp
  #  namespace: eso
  #  id: ClientSecret
externalsecrets:
  ### For Azure Keyvault Secrets containing single value keys the following pattern can be used to declare the target secrets:
  #-
  #  secret: operator-test-secret # Name of the cluster external secret resource
  #  clustersecstore: cluster-azure-backend # Name of the Cluster Secret Store Configured in line2 of this file
  #  namespace: velero # Namespace where the secret will be deployed and managed
  #  namespacesecretname: operator-test # Secret name that will be deployed in the target namespace
  #  namespacesecretkeyname: password # Name that will be given to the key that will be associated to the valued pulled from Azure Keyvault target secret
  #  keyvaultsecretname: operator-test # Name of the target secret in Azure Keyvault that will be pulled into K8S target namespace
  -
    secret: "changeme" # Name of the cluster external secret resource
    argocd: false
    multivalue: true #bollean to indicate if the secret in Azure Keyvault contains multiple keys
    clustersecstore: cluster-azure-backend # Name of the Cluster Secret Store Configured in line2 of this file
    namespace: "" # Namespace where the secret will be deployed and managed
    namespacesecretname: "" # Secret name that will be deployed in the target namespace
    keyvaultsecretname: "" # Name of the target secret in Azure Keyvault that will be pulled into K8S target namespace
