apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clustersecretstore.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  provider:
    {{- if eq .Values.clustersecretstore.providerType "azurekv" }}
    azurekv:
      {{- if .Values.clustersecretstore.azurekv.identityid }}
      authType: ManagedIdentity
      identityId: {{ .Values.clustersecretstore.azurekv.identityid }}
      vaultUrl: {{ .Values.clustersecretstore.azurekv.vaulturl }}
      {{- else }}
      tenantId: {{ .Values.clustersecretstore.azurekv.tenantid }}
      vaultUrl: {{ .Values.clustersecretstore.azurekv.vaulturl }}
      authSecretRef:
        clientId:
          name: {{ .Values.clustersecretstore.azurekv.clientid.name }}
          namespace: {{ .Values.clustersecretstore.azurekv.clientid.namespace }}
          key: {{ .Values.clustersecretstore.azurekv.clientid.id }}
        clientSecret:
          name: {{ .Values.clustersecretstore.azurekv.clientsecret.name }}
          namespace: {{ .Values.clustersecretstore.azurekv.clientsecret.namespace }}
          key:  {{ .Values.clustersecretstore.azurekv.clientsecret.id }}
      {{- end }}
    {{- else if eq .Values.clustersecretstore.providerType "vault" }}
    vault:
      server: {{ .Values.clustersecretstore.vault.server }}
      path: {{ .Values.clustersecretstore.vault.path }}
      version: {{ .Values.clustersecretstore.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.clustersecretstore.vault.auth.tokenName }}
          namespace: {{ .Values.clustersecretstore.vault.auth.tokenNamespace }}
          key: {{ .Values.clustersecretstore.vault.auth.tokenKey }}
    {{- else }}
  {{- end }}
