{{- range $i, $externalsecret := .Values.externalsecrets }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ $externalsecret.secret }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name:  secretsinjector
    meta.helm.sh/release-namespace: external-secrets
spec:
  namespaceSelector:
    {{- if $externalsecret.namespaceSelector }}
    {{- toYaml $externalsecret.namespaceSelector | nindent 4 }}
    {{- else }}
    matchLabels:
      kubernetes.io/metadata.name: {{ $externalsecret.namespace }}
    {{- end }}
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ $externalsecret.clustersecstore }}
    refreshInterval: 5m
    target:
      name: {{ $externalsecret.namespacesecretname }}
      creationPolicy: Owner
    {{- if and ($externalsecret.type) (ne $externalsecret.type "kubernetes.io/tls") }}
      template:
        type: {{ $externalsecret.type}}
        {{- if $externalsecret.labels }}
        metadata:
          labels:
            {{- toYaml $externalsecret.labels | nindent 12 }}
        {{- end }}
        data:
          {{ $externalsecret.namespacesecretkeyname }}: "{{ `{{ .nonopaque }}` }}"
    data:
    - secretKey: nonopaque
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
    {{- else if and ($externalsecret.type) (eq $externalsecret.type "kubernetes.io/tls")}}
      template:
        type: {{ $externalsecret.type}}
        {{- if $externalsecret.labels }}
        metadata:
          labels:
            {{- toYaml $externalsecret.labels | nindent 12 }}
        {{- end }}
        data:
          {{ $externalsecret.namespacesecretkeynamecrt }}: "{{ `{{ .crt }}`}}"
          {{ $externalsecret.namespacesecretkeynamekey }}: "{{ `{{ .key}}`}}"
    data:
    - secretKey: crt
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}-crt
    - secretKey: key
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}-key
    {{- else if and ($externalsecret.contactpoint) (eq $externalsecret.contactpoint true) }}
      template:
        type: Opaque
        metadata:
          labels:
            grafana_alert: "true"
        data:
          contactpoints.yaml: "{{ `{{ .contactpoint }}`}}"
    data:
    - secretKey: contactpoint
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
    {{- else if and ($externalsecret.argocdRepoCreds) (eq $externalsecret.argocdRepoCreds true) }}
      template:
        type: Opaque
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repo-creds
            {{- if $externalsecret.labels }}
            {{- toYaml $externalsecret.labels | nindent 12 }}
            {{- end }}
        data:
          type: "{{ `{{ .type }}` }}"
          url: "{{ `{{ .url }}` }}"
          password: "{{ `{{ .password }}` }}"
          username: "{{ `{{ .username }}` }}"
    data:
    - secretKey: type
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: type
    - secretKey: url
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: url
    - secretKey: password
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: password
    - secretKey: username
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: username
    {{- else if and ($externalsecret.argocd) (eq $externalsecret.argocd true) }}
      template:
        type: Opaque
        metadata:
          labels:
            argocd.argoproj.io/secret-type: cluster
            {{- if $externalsecret.labels }}
            {{- toYaml $externalsecret.labels | nindent 12 }}
            {{- end }}
        data:
          {{- if $externalsecret.argocdBearerToken }}
          name: "{{ `{{ .clusterName }}` }}"
          server: "{{ `{{ .host }}` }}"
          config: '{"bearerToken":"{{ `{{ .bearerToken }}` }}","tlsClientConfig":{"insecure":false,"caData":"{{ `{{ .caData }}` }}"}}'
          {{- else }}
          name: "{{ `{{ .clusterName }}`}}"
          server: "{{ `{{ .host }}`}}"
          config: '{"tlsClientConfig":{"insecure":false,"certData":"{{`{{.certData}}`}}","keyData":"{{`{{ .keyData }}`}}","caData":"{{`{{.caData }}`}}"}}'
          {{- end }}
    data:
    - secretKey: clusterName
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: clusterName
    - secretKey: host
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: host
    - secretKey: caData
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: caData
    {{- if $externalsecret.argocdBearerToken }}
    - secretKey: bearerToken
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: bearerToken
    {{- else }}
    - secretKey: certData
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: certData
    - secretKey: keyData
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: keyData
    {{- end }}
    {{- else if and ($externalsecret.multivalue) (eq $externalsecret.multivalue true) }}
      {{- if $externalsecret.labels }}
      template:
        metadata:
          labels:
            {{- toYaml $externalsecret.labels | nindent 12 }}
      {{- end }}
    dataFrom:
    - extract:
        key: {{ $externalsecret.keyvaultsecretname }}
    {{- else if $externalsecret.property }}
    data:
    - secretKey: {{ $externalsecret.namespacesecretkeyname }}
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
        property: {{ $externalsecret.property }}
    {{- else }}
      {{- if $externalsecret.labels }}
      template:
        metadata:
          labels:
            {{- toYaml $externalsecret.labels | nindent 12 }}
      {{- end }}
    data:
    - secretKey: {{ $externalsecret.namespacesecretkeyname }}
      remoteRef:
        key: {{ $externalsecret.keyvaultsecretname }}
    {{- end }}
{{- end }}
