name: Build Test

on:
  workflow_run:
    workflows: ["Lint and Security Scan"]
    types:
      - completed

jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Directory Structure
        run: ls -la && ls -la chart

      - name: Helm Template Render Test
        working-directory: ./chart
        run: |
          helm template secrets-injector . --debug

      - name: Helm Template Render with Custom Values
        working-directory: ./chart
        run: |
          helm template secrets-injector . \
            --set "clustersecretstore.enabled=true" \
            --debug
