name: Lint and Security Scan

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize 
      - reopened

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Run helm lint
        working-directory: chart
        run: |
          helm lint .

  scan-helm:
    runs-on: ubuntu-latest
    needs: lint-helm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          config_file: checkov.yaml
